### ISSUE TITLE
Sessy Failed to setup

### ISSUE THREAD

**Issue by Borek58** [PimDoos/ha-sessy#130]
After the HA Sessy integration has been working well, it stopped doing it lately.
I did do some updates of HA, but I am not sure if that caused it or not.

**Versions HA**
Installation method
Home Assistant OS
Core
2025.6.0
Supervisor
2025.05.5
Operating System
15.2
Frontend
20250531.2

**Version Sessy**
Sessy Dongle
Er is geen update beschikbaar.
Geïnstalleerde firmwareversie: 1.9.1

Sessy Batterij
Er is geen update beschikbaar.
Geïnstalleerde firmwareversie: 1.9.1

When I deleted it, HA discovers it directly again. After adding both the Donge and the P1, it says again 'Sessy Failed to setup'.

In the log I get an Error and a Warning:

**Error:**
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: June 17, 2025 at 6:21:07 PM (6 occurrences)
Last logged: 11:45:12 AM

Error setting up entry Sessy P1 for sessy
Error setting up entry Sessy Battery DJLC for sessy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sessy/__init__.py", line 78, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(config_entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Warning**
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:335
First occurred: June 17, 2025 at 11:04:13 PM (1 occurrence)
Last logged: June 17, 2025 at 11:04:13 PM

Detected that custom integration 'sessy' sets option flow config_entry explicitly, which is deprecated at custom_components/sessy/config_flow.py, line 156: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/PimDoos/ha-sessy/issues

I hope it make sense, let me know if you need more details.

**Comment by Borek58** [comment]
The sessy integration is 0.6.2 and I see now that there seems to be a version 0.7.
I did use HACS to install it, but can't find a method to update the sessy intergration from it.
Should I remove it and then install the sessy integration again from scratch? There must be a smarter way, isn't?

**Comment by PimDoos** [comment]
0.6 is over a year old. If HACS does not offer you updates, check whether HACS itself is up to date. 

Version 0.8.3 is the latest version. You can manually reinstall it by going to the Sessy integration in HACS and selecting 'redownload'. This will not remove your settings and is equivalent to updating the integration.

**Comment by Borek58** [comment]
HACS is version 2.0.5. In the services it shows the Sessy integration but there is simply not a button or menu to 'redownload'.
This is the HACS download diagnositics 

[config_entry-hacs-01aa1fdff77221a618fdf43e0b3f6fc3.json](https://github.com/user-attachments/files/20800522/config_entry-hacs-01aa1fdff77221a618fdf43e0b3f6fc3.json)

**Comment by Borek58** [comment]
Ah that's what I missed, now I could download it and have the 0.8.3 version installed and is the problem solved.
Thanks for your help!
