### ISSUE TITLE
 type object 'SessyApiCommand' has no attribute 'ENERGY_STATUS'

### ISSUE THREAD

**Issue by momo-maurice** [PimDoos/ha-sessy#103]
Since installing version 0.7.0 (and firmware 1.7.6) the integration is no longer working for (Integration failed to setup). I'm running the sessy in "Open" mode so I rely on HA to charge and uncharge (since I don't have a P1 meter). The logs show the following error on startup:

2024-11-11 11:33:03.248 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sessy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-11 11:33:23.751 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Sessy Battery for sessy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sessy/__init__.py", line 62, in async_setup_entry
    await setup_cache_commands(hass, config_entry, device)
  File "/config/custom_components/sessy/util.py", line 63, in setup_cache_commands
    await setup_cache_command(hass, config_entry, SessyApiCommand.ENERGY_STATUS)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'SessyApiCommand' has no attribute 'ENERGY_STATUS'

**Comment by PimDoos** [comment]
Looks like the sessypy python package was not updated properly. Did you update via HACS or manually?
Can you verify `custom_components/sessy/manifest.json` contains sessypy==0.1.12?

**Comment by momo-maurice** [comment]
I updated through HACS. The manifest looks ok to me:
{
  "domain": "sessy",
  "name": "Sessy",
  "codeowners": [
    "@PimDoos"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/PimDoos/ha-sessy",
  "integration_type": "device",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/PimDoos/ha-sessy/issues",
  "requirements": ["sessypy==0.1.12"],
  "version": "0.7.0",
  "zeroconf":[
    {"type":"_http._tcp.local.","name":"sessy-*"}
  ]
}

**Comment by PimDoos** [comment]
Are you running Home Assistant OS or Core?

**Comment by momo-maurice** [comment]
I'm running  Home Assistant Core 2024.11.1

**Comment by momo-maurice** [comment]
pip list sessypy doesn't list anything, so it looks like it's not installed. I installed it manually with "pip install sessypy" and then I get version 0.1.12, however the problem remains the same. So I downgraded again to 0.6.3 and all is fine (the manual install sessypy 0.1.12 is still there). After upgrade to 0.7.0 I get the same error even with sessypy installed...

**Comment by PimDoos** [comment]
Are you sure you are checking the installed packages in the right venv? 0.6.3 also requires SessyPy, so it should be installed in the venv Home Assistant is running in.

**Comment by momo-maurice** [comment]
I'm running Home assistant in a Kubernetes cluster, so as a seperate container, so I don't think it's a venv as the venv gives the same info as the regular container.

**Comment by momo-maurice** [comment]
It looks like this  an issue with home assistant core itself: https://github.com/home-assistant/core/issues/128214. Since they moved to uv instead of pip, this is broken on containers. The old 0.6.3 version broke whilst upgrading to 2024.12.0.  Removing and reinstalling didn't work anymore. Finally I got it working with running 'uv pip install sessypy' manually. However looking at the issue this will probably break again at the next upgrade.

**Comment by PimDoos** [comment]
OK, so it looks like this is not an issue with SessyPy but an issue upstream in core. I'll close the issue here.
